name: Weekly LLVM Release Check
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "LLVM Version"
        required: false
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get LLVM version
      run: |
        if [[ -z $github_event_inputs_tag_name ]]; then
          tag_name=$(curl -sL https://api.github.com/repos/llvm/llvm-project/releases/latest | jq -r '.tag_name')
        else
          tag_name=$github.event.inputs.tag_name
        fi

        echo "Using version: $tag_name"       
        echo "tag_name=${tag_name}" >> $GITHUB_ENV
        version=$(echo $tag_name | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "version=${version}" >> $GITHUB_ENV
        major_version=$(echo $version | awk -F '.' '{print $1}')
        echo "major_version=${major_version}" >> $GITHUB_ENV
        branch_version='release/'$major_version'.x'
        echo "branch_version=${branch_version}" >> $GITHUB_ENV
        is_official_release=$(curl -sL https://api.github.com/repos/llvm/llvm-project/releases/latest | jq -r '.prerelease')
        echo "is_official_release=${is_official_release}" >> $GITHUB_ENV
        branch_exists=$(git ls-remote --exit-code --heads llvm-capstone $branch_version)
        echo "branch_exists=${branch_exists}" >> $GITHUB_ENV

    - name: Ensure official release
      run: |
        if [[ "${{ env.is_official_release }}" != "false" ]]; then
          exit 0
        fi

    - name: Checkout LLVM-project ${{ env.branch_version }}
      uses: actions/checkout@v3
      with:
        repository: 'llvm/llvm-project'
        ref: ${{ env.branch_version }}

    - name: Commit new branch
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote add llvm-capstone https://github.com/${{ github.repository }}
        echo "fetch llvm-capstone"
        git fetch llvm-capstone 
        echo "sparse checkout"
        git sparse-checkout init --cone
        git sparse-checkout set llvm/ cmake/ third-party/
        git add *
        ls

    - name: Update branch ${{ env.branch_version }}
      if: ${{ env.branch_exists }}
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Branch already exists, update."
          git commit -m "Update LLVM ${{ env.branch_version }}"
        else
          echo "No changes to commit."
          exit 0
        fi

    - name: Commit new branch ${{ env.branch_version }}
      if: ! ${{ env.branch_exists }}
      run: |
        git commit -m "Add LLVM ${{ env.branch_version }}"

    - name: Push new branch
      run: |
        git push llvm-capstone ${{ env.branch_version }} --force

